version: 2

sphinx:
  configuration: docs/conf.py

build:
    os: ubuntu-20.04
    tools:
        python: '3.10'

python:
  install:
    - requirements: docs-requirements.txt
    - requirements: requirements.txt
