FROM python:3.5

RUN mkdir /src
WORKDIR /src

COPY requirements.txt /src/requirements.txt
RUN pip install -r requirements.txt

COPY docs-requirements.txt /src/docs-requirements.txt
RUN pip install -r docs-requirements.txt

COPY . /src
