FROM python:3.5

RUN mkdir /home/docker-py
WORKDIR /home/docker-py

COPY requirements.txt /home/docker-py/requirements.txt
RUN pip install -r requirements.txt

COPY docs-requirements.txt /home/docker-py/docs-requirements.txt
RUN pip install -r docs-requirements.txt

COPY . /home/docker-py
