# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: filesync.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import filesync_pb2


class FileSyncBase(abc.ABC):

    @abc.abstractmethod
    async def DiffCopy(self, stream):
        pass

    @abc.abstractmethod
    async def TarStream(self, stream):
        pass

    def __mapping__(self):
        return {
            '/moby.filesync.v1.FileSync/DiffCopy': grpclib.const.Handler(
                self.DiffCopy,
                grpclib.const.Cardinality.STREAM_STREAM,
                filesync_pb2.BytesMessage,
                filesync_pb2.BytesMessage,
            ),
            '/moby.filesync.v1.FileSync/TarStream': grpclib.const.Handler(
                self.TarStream,
                grpclib.const.Cardinality.STREAM_STREAM,
                filesync_pb2.BytesMessage,
                filesync_pb2.BytesMessage,
            ),
        }


class FileSyncStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.DiffCopy = grpclib.client.StreamStreamMethod(
            channel,
            '/moby.filesync.v1.FileSync/DiffCopy',
            filesync_pb2.BytesMessage,
            filesync_pb2.BytesMessage,
        )
        self.TarStream = grpclib.client.StreamStreamMethod(
            channel,
            '/moby.filesync.v1.FileSync/TarStream',
            filesync_pb2.BytesMessage,
            filesync_pb2.BytesMessage,
        )


class FileSendBase(abc.ABC):

    @abc.abstractmethod
    async def DiffCopy(self, stream):
        pass

    def __mapping__(self):
        return {
            '/moby.filesync.v1.FileSend/DiffCopy': grpclib.const.Handler(
                self.DiffCopy,
                grpclib.const.Cardinality.STREAM_STREAM,
                filesync_pb2.BytesMessage,
                filesync_pb2.BytesMessage,
            ),
        }


class FileSendStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.DiffCopy = grpclib.client.StreamStreamMethod(
            channel,
            '/moby.filesync.v1.FileSend/DiffCopy',
            filesync_pb2.BytesMessage,
            filesync_pb2.BytesMessage,
        )
