# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filesync.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='filesync.proto',
  package='moby.filesync.v1',
  syntax='proto3',
  serialized_options=_b('Z\010filesync'),
  serialized_pb=_b('\n\x0e\x66ilesync.proto\x12\x10moby.filesync.v1\"\x1c\n\x0c\x42ytesMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xab\x01\n\x08\x46ileSync\x12N\n\x08\x44iffCopy\x12\x1e.moby.filesync.v1.BytesMessage\x1a\x1e.moby.filesync.v1.BytesMessage(\x01\x30\x01\x12O\n\tTarStream\x12\x1e.moby.filesync.v1.BytesMessage\x1a\x1e.moby.filesync.v1.BytesMessage(\x01\x30\x01\x32Z\n\x08\x46ileSend\x12N\n\x08\x44iffCopy\x12\x1e.moby.filesync.v1.BytesMessage\x1a\x1e.moby.filesync.v1.BytesMessage(\x01\x30\x01\x42\nZ\x08\x66ilesyncb\x06proto3')
)




_BYTESMESSAGE = _descriptor.Descriptor(
  name='BytesMessage',
  full_name='moby.filesync.v1.BytesMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='moby.filesync.v1.BytesMessage.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=64,
)

DESCRIPTOR.message_types_by_name['BytesMessage'] = _BYTESMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BytesMessage = _reflection.GeneratedProtocolMessageType('BytesMessage', (_message.Message,), dict(
  DESCRIPTOR = _BYTESMESSAGE,
  __module__ = 'filesync_pb2'
  # @@protoc_insertion_point(class_scope:moby.filesync.v1.BytesMessage)
  ))
_sym_db.RegisterMessage(BytesMessage)


DESCRIPTOR._options = None

_FILESYNC = _descriptor.ServiceDescriptor(
  name='FileSync',
  full_name='moby.filesync.v1.FileSync',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=67,
  serialized_end=238,
  methods=[
  _descriptor.MethodDescriptor(
    name='DiffCopy',
    full_name='moby.filesync.v1.FileSync.DiffCopy',
    index=0,
    containing_service=None,
    input_type=_BYTESMESSAGE,
    output_type=_BYTESMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TarStream',
    full_name='moby.filesync.v1.FileSync.TarStream',
    index=1,
    containing_service=None,
    input_type=_BYTESMESSAGE,
    output_type=_BYTESMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILESYNC)

DESCRIPTOR.services_by_name['FileSync'] = _FILESYNC


_FILESEND = _descriptor.ServiceDescriptor(
  name='FileSend',
  full_name='moby.filesync.v1.FileSend',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=240,
  serialized_end=330,
  methods=[
  _descriptor.MethodDescriptor(
    name='DiffCopy',
    full_name='moby.filesync.v1.FileSend.DiffCopy',
    index=0,
    containing_service=None,
    input_type=_BYTESMESSAGE,
    output_type=_BYTESMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILESEND)

DESCRIPTOR.services_by_name['FileSend'] = _FILESEND

# @@protoc_insertion_point(module_scope)
